//photos
export const GET_PHOTOS_START = 'GET_PHOTOS_START';
export const GET_PHOTOS_SUCCES = 'GET_PHOTOS_SUCCES';
export const GET_PHOTOS_ERROR = 'GET_PHOTOS_ERROR';

//saved searches
export const SAVE_SEARCH_SUCCESS = 'SAVE_SEARCH_SUCCESS';
export const CLEAR_ALL_SEARCHES_SUCCESS = 'CLEAR_ALL_SEARCHES_SUCCESS';
